/*
 * Copyright (C) 2023 Spanning Cloud Apps.  All rights reserved
 */

const en = {
  POOPER_AI: 'Pooper AI',
  LOGIN_BUTTON: 'Login',
  TICKETS: 'Tickets',
  WORKFLOWS: 'Workflows',





  SCARMIN_LOGIN_TITLE: 'SCARMIN',
  HEADER_TITLE: 'US Admin',
  SIDER_TITLE: 'Scarmin',
  SIDEBAR_DOMAINS: 'Domains',
  SIDEBAR_USERS: 'Users',
  SIDEBAR_PROBLEMS: 'Problems',
  DASHBOARD: 'Dashboard',
  AUTHENTICATE: 'Authenticate',
  NAVIGATION: 'NAVIGATION',
  SUCCESS: 'Success',
  SUCCESSFUL: 'Successful',
  FAILED: 'Failed',
  PARTIAL: 'Partial',
  NOT_RUN: 'Not run',
  HAS_SKIPPED_ITEMS: 'Has skipped items',
  HAS_FAILED_ITEMS: 'Has failed items',
  ABORTED: 'Aborted',
  UNKNOWN: 'Unknown',
  ERROR: 'Error',
  UNKNOWN_ERROR: 'Unknown error',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  RELOAD_PAGE: 'Reload page',
  NOTIFICATION_COPY_MESSAGE: 'Copy Message',
  PAGE_NOT_FOUND: 'Not Found',
  PAGE_ERROR: 'Unknown Error',
  CACHE_SYNC: 'Sync on {date} is {status}',
  CACHE_SYNC_CREATED: 'created',
  CACHE_SYNC_COMPLETED: 'completed',
  CACHE_SYNC_LOADING_USERS: 'loading users',
  CACHE_SYNC_LOADING_ORG_UNITS: 'loading org units',
  CACHE_SYNC_LOADING_ORG_USERS: 'loading org users',

  TIME_WIDGET_UTC_LABEL: 'UTC',
  TIME_WIDGET_LOCAL_LABEL: 'Locale time',

  DOMAINS_BLOCK_TITLE: 'Domains',
  DOMAINS_HEADER_LOGOUT_BUTTON: 'Logout',
  USERS_BLOCK_TITLE: 'Users',

  ACTIVITIES_TITLE: 'Activity Info',
  ACTIVITIES_BACK_TEXT: 'Back to Tenant',
  ACTIVITY_END_DATE_FROM: 'From',
  ACTIVITY_END_DATE_TO: 'To',
  ACTIVITY_FILTER_BACKUP: 'Manual Backup',
  ACTIVITY_FILTER_EXPORT: 'Export',
  ACTIVITY_FILTER_RESTORE: 'Restore',
  ACTIVITY_FILTER_ADMINISTRATIVE: 'Administrative',
  ACTIVITY_END_DATE_COLUMN: 'End Date',
  ACTIVITY_START_DATE_COLUMN: 'Start Date',
  ACTIVITY_EVENT_COLUMN: 'Event',
  ACTIVITY_ACTOR_USER_COLUMN: 'Users',
  ACTIVITY_RESULT_COLUMN: 'Result',

  BATCH_TABLE_COLUMN_BACKUP_BATCH_ID: 'Backup Batch ID',
  BATCH_TABLE_COLUMN_EXPORT_BATCH_ID: 'Export Batch ID',
  BATCH_TABLE_COLUMN_RESTORE_BATCH_ID: 'Restore Batch ID',
  BATCH_TABLE_COLUMN_JOB_ID: 'Job ID',
  BATCH_TABLE_COLUMN_PARTITION_ID: 'Partition ID',
  BATCH_TABLE_COLUMN_VIEWABLE: 'Viewable?',
  BATCH_TABLE_COLUMN_START_TIME: 'Start Time',
  BATCH_TABLE_COLUMN_END_TIME: 'End Time',
  BATCH_TABLE_COLUMN_RESULT: 'Result',

  DOMAIN_STORAGE_PAGE_TITLE: 'Storage',
  DOMAIN_STORAGE_REPORTS_WIDGET_TITLE: 'Storage',
  DOMAIN_STORAGE_REPORTS_DASHBOARD_TITLE: 'Storage',
  DOMAIN_STORAGE_REPORTS_USED_TAG: 'Stored: {value}',
  DOMAIN_STORAGE_REPORTS_NOTE_ACCURACY: 'Deviation of calculations by metrics no more than 10%',
  DOMAIN_STORAGE_REPORTS_ERROR: 'Loading Error Domain Storage Reports',
  DOMAIN_STORAGE_REPORTS_WIDGET_COLUMN_OBJECT: 'Storage Object',
  DOMAIN_STORAGE_REPORTS_WIDGET_COLUMN_SIZE: 'Size',
  DOMAIN_STORAGE_REPORTS_WIDGET_COLUMN_UPDATE: 'Last Update',
  DOMAIN_STORAGE_REPORTS_WIDGET_INFO_GOOGLE: 'Google - downloaded from Google',
  DOMAIN_STORAGE_REPORTS_WIDGET_INFO_S3: 'S3 - stored and compressed in S3',
  DOMAIN_STORAGE_REPORTS_TITLE: 'Tenant Storage',
  DOMAIN_STORAGE_REPORTS_DAILY_TITLE: 'Δ Daily Storage',
  DOMAIN_STORAGE_REPORTS_TOTAL_TITLE: 'Total Storage',
  DOMAIN_STORAGE_REPORTS_COMPRESS_TITLE: 'Compression Efficiency',
  DOMAIN_STORAGE_REPORTS_DETAILS_LINK: 'See Details',
  DOMAIN_STORAGE_INFO_IS_MISSING: 'Information about storage is missing',
  DOMAIN_TOTAL_STORAGE_S3: 'Total (S3)',
  DOMAIN_TOTAL_STORAGE_GOOGLE: 'Total (Google)',
  DOMAIN_MAIL_STORAGE_S3: 'Mail (S3)',
  DOMAIN_MAIL_STORAGE_GOOGLE: 'Mail (Google)',
  DOMAIN_CALENDAR_STORAGE_S3: 'Calendar (S3)',
  DOMAIN_CALENDAR_STORAGE_GOOGLE: 'Calendar (Google)',
  DOMAIN_CONTACT_STORAGE_S3: 'Contact (S3)',
  DOMAIN_CONTACT_STORAGE_GOOGLE: 'Contact (Google)',
  DOMAIN_DOCUMENT_STORAGE_S3: 'Drive (S3)',
  DOMAIN_DOCUMENT_STORAGE_GOOGLE: 'Drive (Google)',
  DOMAIN_SITE_STORAGE_S3: 'Site (S3)',
  DOMAIN_SITE_STORAGE_GOOGLE: 'Site (Google)',
  DOMAIN_STORAGE_REPORT_CHART_FIELD_TOTAL_GOOGLE: 'Google Total Downloaded',
  DOMAIN_STORAGE_REPORT_CHART_FIELD_TOTAL_S3: 'S3 Total Stored',
  DOMAIN_STORAGE_REPORT_CHART_FIELD_STORED_GOOGLE: 'Google Downloaded',
  DOMAIN_STORAGE_REPORT_CHART_FIELD_STORED_S3: 'S3 Stored',
  DOMAIN_STORAGE_REPORT_CHART_FIELD_REAPED_S3: 'S3 Reaped',
  DOMAIN_STORAGE_REPORT_CHART_FIELD_RETENTION_S3: 'S3 Retention',
  DOMAIN_STORAGE_REPORT_CHART_FIELD_COMPRESS: 'Compression Efficiency',

  DOMAINS_TABLE_COLUMN_ID: 'Id',
  DOMAINS_TABLE_COLUMN_NAME: 'Display Name',
  DOMAINS_TABLE_COLUMN_RESELLER: 'Reseller',
  DOMAINS_TABLE_COLUMN_STATUS: 'Status',
  DOMAINS_TABLE_COLUMN_NUM_USERS: 'Num Users',
  DOMAINS_TABLE_COLUMN_LICENSES: 'Licenses',
  DOMAINS_TABLE_COLUMN_CREATED_AT: 'Created At',
  DOMAINS_TABLE_COLUMN_EXPIRES_AT: 'Expires At',
  DOMAINS_TABLE_COLUMN_EXPIRED_FROM: 'Expired From',
  DOMAINS_TABLE_COLUMN_EXPIRED_TO: 'Expired To',
  DOMAINS_TABLE_COLUMN_TAGS: 'Tags',

  TABLE_LOADING: 'Loading ...',

  TABLE_TOOLS_EXPIRED_FROM: 'Expired From',
  TABLE_TOOLS_EXPIRED_TO: 'Expired To',
  TABLE_TOOLS_SEARCH_PLACEHOLDER: 'Search...',
  TABLE_TOOLS_DROPDOWN_ITEM_1: 'Expires Today',
  TABLE_TOOLS_DROPDOWN_ITEM_2: 'Expires In Two Weeks',
  TABLE_TOOLS_DROPDOWN_ITEM_3: 'Expires In One Month',
  TABLE_TOOLS_DROPDOWN_ITEM_4: 'Expired all',
  TABLE_TOOLS_DROPDOWN_BUTTON: 'Shortcuts',
  TABLE_TOOLS_PAID: 'Paid',
  TABLE_TOOLS_TRIAL: 'Trial',

  HAS_NO_RESULT: 'Query has no result',

  INTERNAL_ERROR: 'Internal Error',

  DOMAIN_BACKUP_NET_ORG_NAME_LABEL: 'Backup.net Organization',
  DOMAIN_BACKUP_NET_ORG_ID_LABEL: 'Backup.net Organization Id',
  DOMAIN_READONLY_INFO: 'Domain Read-only Info',
  DOMAIN_EDITABLE_INFO: 'Domain Editable Info',
  DOMAIN_DISPLAY_NAME_LABEL: 'Display Name',
  DOMAIN_ID_LABEL: 'Domain ID',
  DOMAIN_LICENCE_TYPE_LABEL: 'License Type',
  DOMAIN_SUBSCR_STARTED_LABEL: 'Subscription Started',
  DOMAIN_SUBSCR_ENDS_LABEL: 'Subscription Ends',
  DOMAINS_UPDATED_AT_LABEL: 'Updated At',

  DOMAIN_ADMIN_EMAIL_LABEL: 'Admin Email',
  DOMAIN_NOTES_LABEL: 'Notes',
  DOMAIN_PAID_SEATS_LABEL: 'Paid Seats',
  DOMAIN_ACTIVE_SEATS_LABEL: 'Active Seats',
  DOMAIN_TAGS_LABEL: 'Tags',
  DOMAIN_STRIPE_COSTOMER_ID_LABEL: 'Stripe Customer Id',
  DOMAIN_ADMINS_LABEL: 'Domain Admins',
  SUBDOMAINS_LABEL: 'Subdomains',
  DOMAIN_ADMINS_BUTTON_LABEL: 'Domain Admins',
  DOMAIN_DATA_COPY_TOOLTIP_LABEL: 'Click to show full JSON',
  DOMAIN_SYNC_USERS: 'Sync Domain',
  DOMAIN_K1_ORGANIZATION_ID: 'K1 Organization Id',
  DOMAIN_ONBOARD_NAME: 'Onboard Domain Name',
  DOMAIN_OLD_NAMES: 'Domain Old Names',
  DOMAIN_UPSELL_EC_CONTRACT: 'Up-sell Id (ecContract)',
  DOMAIN_OLD_NAMES_LABEL: 'Old Names',

  DOMAIN_TAG_NOT_REAPED_LABEL: 'Not Reaped',
  DOMAIN_NOT_EXPIRED_LABEL: 'Not Expired',
  DOMAIN_EXPIRED_LABEL: 'Expired',
  DOMAIN_REAPED_LABEL: 'Reaped',
  DOMAIN_TRIAL_LABEL: 'Trial',
  DOMAIN_PAID_LABEL: 'Paid',

  DOMAIN_DATA_DRAWER_COPY_LABEL: 'Copy all Domain data',
  DOMAIN_DETAILED_PAGE_TITLE: 'Domain',
  DOMAIN_DSYNC_BUTTON_TITLE: 'Sync domain to salesforce',
  DOMAIN_CACHE_REFRESH_BUTTON_TITLE: 'Refresh Domain Cache',
  DOMAIN_USERS_PAGE_TITLE: 'Cache Users',

  DOMAIN_STATUS_LABEL: 'Status',
  DOMAIN_CHANGE_TO_TRIAL_BUTTON_LABEL: 'Set To Trial',
  DOMAIN_CHANGE_TO_PAID_BUTTON_LABEL: 'Set To Paid',
  DOMAIN_PURCHASE_ENABLED_LABEL: 'Purchase Enabled',
  DOMAIN_PURCHASE_SAVE_BUTTON_LABEL: 'Save',
  DOMAIN_BILLING_TYPE_LABEL: 'Billing Type',
  DOMAIN_EXPAIRED_AT_LABEL: 'Expired At',
  DOMAIN_LICENSES_LABEL: 'Licenses',
  DOMAIN_RESELLER_LABEL: 'Reseller',
  DOMAIN_KMS_ARN_LABEL: 'KMS ARN',
  DOMAIN_KMS_ARN_HELP_MESSAGE: 'KMS ARN could be updated only for reaped domains',

  DOMAIN_UPDATE_EXPIRATION_DATE_MODAL_TITLE: 'Update domain expiration date',
  DOMAIN_UPDATE_EXPIRATION_DATE_MODAL_CURR_EXPIRATION_DATE: 'Current expiration date:',
  DOMAIN_UPDATE_EXPIRATION_DATE_MODAL_NEW_EXPIRATION_DATE: 'New expiration date:',
  DOMAIN_UPDATE_EXPIRATION_DATE_MODAL_NEW_REAP_DATE: 'After these changes domain\'s data will be reaped:',
  DOMAIN_UPDATE_EXPIRATION_DATE_MODAL_REQUIRED_INPUT: 'You should fill the input below with "I understand that data will be reaped earlier"',
  DOMAIN_UPDATE_EXPIRATION_DATE_MODAL_CONFIRM_MESSAGE: 'I understand that data will be reaped earlier',
  DOMAIN_UPDATE_EXPIRATION_DATE_MODAL_REQUIRED_TEXTAREA: 'Please put a link to a quote or ticket where past date was requested and approved',

  CARD_WIDGET_AUTH_INFO_TITLE: 'Auth Info',
  CARD_WIDGET_ADMIN_EMAIL: 'Admin Email',
  CARD_WIDGET_ENABLED: 'enabled',
  CARD_WIDGET_DISABLED: 'disabled',
  CARD_WIDGET_USERS_TITLE: 'Users',
  CARD_WIDGET_ASSIGNED_USERS_LABEL: 'Assigned',
  CARD_WIDGET_USERS_CACHE_NOT_RUN_LABEL: 'There were no successful syncs',
  CARD_WIDGET_USERS_CACHE_LABEL: 'Cache',
  CARD_WIDGET_GOOGLE_USERS_LABEL: 'Google users',
  CARD_WIDGET_SETTINGS_TITLE: 'Settings',
  CARD_WIDGET_NO_SETTINGS_TITLE: 'No backup settings',
  CARD_WIDGET_BACKUP_SHARED_SETTINGS: 'Backup shared settings',
  CARD_WIDGET_ACCOUNTS: 'Accounts',
  CARD_WIDGET_LICENSE_MANAGEMENT_TITLE: 'Users management',
  CARD_WIDGET_LICENSES: 'Licenses',
  CARD_WIDGET_PROTECTED: 'Protected users',
  CARD_WIDGET_NUM_USERS: 'Num users',
  CARD_WIDGET_UNPROTECTED: 'Unprotected users',
  CARD_WIDGET_ZOMBIES: 'Zombies',
  CARD_WIDGET_UNUSED_LICENSES: 'Unused licenses',
  CARD_WIDGET_INSTALL_DATE: 'Installation date',
  RESELLER_UPDATE_MESSAGE: 'I understand that the licenses for this domain and the Reseller need to be reconciled manually',
  RESELLER_WARN_MODAL_TITLE: 'Confirm',
  RESELLER_WARN_MODAL_QUESTION: 'Are you certain you want to change the Reseller ID?',
  RESELLER_WARN_MODAL_REMOVE_QUESTION: 'Are you certain you want to remove the Reseller ID?',
  SYNC_DOMAIN_NOTIFICATION: 'Synced domain to Salesforce',
  SYNC_DOMAIN_CACHE_UPDATED: 'Users cache update request had been sent',
  NO_DATA: 'No data',
  NOT_AVAILABLE: 'N/A',
  TRIAL_WARNING: 'The number of assigned users ({assignedUsers}) is greater than the number of trial licenses ({trialLicenses})',

  REPORTS_METRICS_PERIODS_7: 'Last 7 Days',
  REPORTS_METRICS_PERIODS_14: 'Last 14 Days',
  REPORTS_METRICS_PERIODS_30: 'Last 30 Days',
  REPORTS_METRICS_COLLAPSE_TOOLTIP: 'Show Or Hide Card',

  TOP_MENU_COMMON_TAB: 'Common Info',
  TOP_MENU_USER_TAB: 'Users',
  TOP_MENU_ACTIVITY_TAB: 'Activity',
  TOP_MENU_RETENTION_TAB: 'Retention',
  TOP_MENU_DARKWEB_TAB: 'Darkweb',
  TOP_MENU_FEATURES_TAB: 'Features',

  CACHE_USERS_ASSIGNED_FILTER: 'Assigned',
  CACHE_USERS_GOOGLE_SUPER_ADMIN_FILTER: 'Google super admins',
  CACHE_USERS_SPANNING_SUPER_ADMIN_FILTER: 'Spanning super admins',
  CACHE_USERS_HELP_DESK_ADMIN_FILTER: 'Help desk admins',

  CACHE_USERS_TABLE_COLUMN_DISPLAY_NAME: 'Display Name',
  CACHE_USERS_TABLE_COLUMN_UPC: 'User Principal Name',
  CACHE_USERS_TABLE_COLUMN_GID: 'GID',
  CACHE_USERS_TABLE_COLUMN_TAGS: 'Tags',
  CACHE_USERS_TABLE_COLUMN_ASSIGNED: 'Assigned',
  CACHE_USERS_TABLE_ADMIN_TAG: 'Admin',
  CACHE_USERS_TABLE_ZOMBIE_TAG: 'Zombie',

  USERS_FILTER_ASSIGNED: 'Assigned',
  USERS_FILTER_SUSPENDED_ONLY: 'Suspended ',
  USERS_FILTER_GOOGLE_ADMIN_ONLY: 'Google Admin',
  USERS_FILTER_SPANNING_ADMIN_ONLY: 'Spanning Admin',
  USERS_FILTER_HELP_DESK_ADMIN_ONLY: 'Help Desk Admin',
  USERS_FILTER_DELETED_ONLY: 'Deleted',

  USERS_TABLE_COLUMN_ID: 'Id',
  USERS_TABLE_COLUMN_DOMAIN_ID: 'Domain Id',
  USERS_TABLE_COLUMN_UPN: 'User Principal Name',
  USERS_TABLE_COLUMN_DISPLAY_NAME: 'Display Name',
  USERS_TABLE_COLUMN_CREATED_AT: 'Created at',
  USERS_TABLE_COLUMN_TAGS: 'Tags',
  USERS_TABLE_COLUMN_ASSIGNED_TAG: 'Assigned',
  USERS_TABLE_COLUMN_ZOMBIE_TAG: 'Zombie',
  USERS_TABLE_COLUMN_ARCHIVED_TAG: 'Archived',

  DOMAIN_RETENTION_PAGE_TITLE: 'Retention',
  DOMAIN_RETENTION_WIDGET_TITLE: 'Retention settings',
  PLEASE_INPUT_NUMBER_OF_DAYS: 'Please input number of days',
  RETENTION_FORM_ENABLE_DISCLAIMER: 'I understand that SUBMIT {policyType} RETENTION will DELETE DATA older than {numDays} {numDays, plural, =1 {day} other {days}}.',
  RETENTION_FIELD_IS_REQUIRED: 'This field is required',
  RETENTION_LIMIT_MAX: 'Retention period should be less than {limit} days',
  RETENTION_LIMIT_MIN: 'Retention period should be more than 30 days',
  RETENTION_REQUESTED_BY_PLACEHOLDER: 'Enter who proposed this changes',
  RETENTION_LIMIT_DAYS: ' {limit, plural, =1 {day} other {days}}',
  RETENTION_DRAWER_TITLE: 'Retention {type}',
  RETENTION_TABLE_COLUMN_TYPE: 'Type',
  RETENTION_TABLE_COLUMN_STATUS: 'Status',
  RETENTION_TABLE_COLUMN_LIMIT: 'Limit',
  REQUESTED_BY: 'Requested By',
  RETENTION_TABLE_COLUMN_ACTION: 'Action',
  RETENTION_POLICY_UPDATED_NOTIFICATION: 'Retention {policyType} was successfully updated',
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  SUBMIT: 'SUBMIT',
  ON: 'ON',
  OFF: 'OFF',
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
  MAIL: 'Mail',
  DOCUMENT: 'Document',
  CONTACT: 'Contact',
  CALENDAR: 'Calendar',
  SITE: 'Site',

  DOMAIN_FEATURES_PAGE_TITLE: 'Feature settings',
  FEATURES_TABLE_FEATURE_NAME: 'Feature Type',
  FEATURES_TABLE_STATUS: 'Feature Status',
  FEATURES_TABLE_CREATED_AT: 'Created At(UTC)',
  FEATURES_TABLE_UPDATED_AT: 'Updated At(UTC)',
  FEATURES_TABLE_ENABLED_AT: 'Enabled At(UTC)',
  FEATURES_TABLE_DISABLED_AT: 'Disabled At(UTC)',
  FEATURES_TABLE_REAPED: 'Reaped',
  FEATURES_TABLE_NOT_REAPED: 'Not reaped',
  FEATURE_TABLE_SETTINGS: 'Settings',
  FEATURE_DRAWER_TITLE: 'Feature {name}',
  FEATURE_REFRESH_BUTTON: 'Refresh Features',
  FEATURE_DROP_DARKWEB_BUTTON: 'Drop Darkweb feature',
  FEATURE_INIT_DARKWEB_BUTTON: 'Init Darkweb feature',
  REAPED: 'Reaped',
  NOT_REAPED: 'Not Reaped',
  FEATURE_AUTO_ASSIGN: 'Auto-assign',
  FEATURE_AUTO_ASSIGN_NOTE: 'Automatically Backup New {featureName}',
  FEATURE_AUTO_PURCHASE: 'Auto-purchase',
  FEATURE_AUTO_PURCHASE_DISCLAIMER: 'The Auto-purchase feature is not configured properly. Please raise a Support ticket or turn this feature off.',
  FEATURE_DOCUMENT: 'Document',
  FEATURE_CALENDAR: 'Calendar',
  FEATURE_CONTACT: 'Contact',
  FEATURE_MAIL: 'Mail',
  FEATURE_ENCRYPT: 'Encrypt',
  FEATURE_SETTINGS: 'Settings',
  FEATURE_MAIL_PREVIEW: 'Mail Preview',
  FEATURE_SITE: 'Site',
  FEATURE_DOMAIN_REAPED: 'Domain Reaped',
  FEATURE_ADMIN_ONLY_EXPORT: 'Admin Only Export',
  FEATURE_ADMIN_ONLY_LOGIN: 'Admin Only Login',
  FEATURE_TEAM_DRIVES: 'Team Drives',
  FEATURE_STORAGE_DATA: 'Storage Data',
  FEATURE_DOMAIN_USER_RENAME: 'Domain User Rename',
  FEATURE_DARKWEB: 'Darkweb',
  FEATURE_DARKWEB_DISCLAIMER: 'Darkweb feature functionality is available only for invoiced domains without reseller. Please pay attention on it during Darkweb feature management.',
  FEATURE_IT_COMPLETE: 'IT Complete',
  FEATURE_RELEASE_NOTES: 'Release Notes',
  FEATURE_INTERCOM_NOTIFICATION: 'Intercom Notification',
  FEATURE_DROP_BUTTON_LABEL: 'Drop {featureName} feature',
  FEATURE_INIT_BUTTON_LABEL: 'Init {featureName} feature',
  FEATURE_INFO_TOGGLE_BUTTON_LABEL: ' {featureName} feature',
  FEATURE_INFO_REFRESH: 'Refresh Features',
  DISABLE: 'Disable',
  ENABLE: 'Enable',
  FEATURE_INFO_NOTIFICATION_ENABLED: 'Feature {featureName} was enabled ',
  FEATURE_INFO_NOTIFICATION_DISABLED: 'Feature {featureName} was disabled',
  FEATURE_INFO_NOTIFICATION_UPDATED_DATE: 'Disabled At date was updated for feature {featureName} ',
  FEATURE_INFO_NOTIFICATION_INIT: 'Feature {featureName} was initialized',
  FEATURE_INFO_NOTIFICATION_DROPPED: 'Feature {featureName} was dropped',
  FEATURE_INFO_NOTIFICATION_UPDATED_SETTINGS: '{settingName} was updated in Feature {featureName} ',
  FEATURE_INFO_SELECT_TIME: 'Select Time',
  SAVE: 'Save',

  DOMAINS_BACK_TEXT: 'Back to domains',
  DOMAIN_BACK_TEXT: 'Back to domain',
  USERS_BACK_TEXT: 'Back to users',

  EMAIL_DROPDOWN_TITLE: 'Email',
  PERMISSIONS_DROPDOWN_TITLE: 'Permissions',
  READONLY_ROLE: 'read-only',
  ADMIN_ROLE: 'admin',
  PROD_SUPPORT_ROLE: 'prod-support',

  HEADER_LOGOUT: 'Log Out',

  USER_INFO_TITLE: 'User Info',

  USER_DETAILS_DISPLAY_NAME_LABEL: 'Display Name',
  USER_DETAILS_PRINCIPAL_NAME_LABEL: 'Principal Name',
  USER_DETAILS_ASSIGNED_LABEL: 'Assigned',
  USER_DETAILS_SPANNING_ADMIN_LABEL: 'Spanning Admin',
  USER_DETAILS_GOOGLE_ADMIN_LABEL: 'Google Admin',
  USER_DETAILS_HELP_DESK_ADMIN_LABEL: 'Help Desk Admin',
  USER_DETAILS_ID_LABEL: 'Id',
  USER_DETAILS_GID_LABEL: 'GID',
  USER_DETAILS_DOMAIN_ID_LABEL: 'Domain Id',
  USER_DETAILS_CREATED_AT_LABEL: 'Created At',
  USER_DETAILS_UPDATED_AT_LABEL: 'Updated At',
  USER_DETAILS_ASSIGNED_AT_LABEL: 'Assigned At',
  USER_DETAILS_UNASSIGNED_AT_LABEL: 'Unassigned At',
  USER_DETAILS_GOOGLE_DELETED_AT_LABEL: 'Google Deleted At',
  USER_DETAILS_GOOGLE_SUSPENDED_AT_LABEL: 'Google Suspended At',
  USER_DETAILS_SEARCH_DATA: 'Search Data',
  USER_DETAILS_DATA: 'Data',
  USER_DETAILS_PARTITION_ID: 'Partition Id',
  USER_DETAILS_REAPED_LABEL: 'Reaped',
  USER_DETAILS_NOT_REAPED_LABEL: 'Not Reaped',
  USER_DETAILS_EXPIRED_LABEL: 'Expired',
  USER_DETAILS_ZOMBIE_LABEL: 'Zombie',
  USER_DETAILS_GOOGLE_DELETED: 'Google Deleted',
  USER_DETAILS_GOOGLE_SUSPENDED: 'Google Suspended',
  USER_DETAILS_FEATURES: 'Features',
  USER_FEATURE_MAIL: 'Mail',
  USER_FEATURE_CONTACT: 'Contact',
  USER_FEATURE_SITE: 'Site',
  USER_FEATURE_CALENDAR: 'Calendar',
  USER_FEATURE_DOCUMENT: 'Document',
  USER_DETAILS_TAGS: 'Tags',

  NOTIFICATION_SUBJECT_DOMAIN: 'Get info for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_INSTALLER: 'Get installer info for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_CACHE: 'Get cache for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_USERS_MANAGEMENT_INFO: 'Get users management info for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_SYNC_SALESFORCE: 'Sync to SalesForce for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_UPDATE_BILLING_TYPE: 'Update billing type for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_UPDATE_INFO: 'Update info for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_SYNC_CACHE: 'Sync cache for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAINS_LIST: 'Get list of domains',
  NOTIFICATION_SUBJECT_DOMAINS_PAYMENT_STATUS: 'Get payment status for domains',
  NOTIFICATION_SUBJECT_DOMAIN_ACTIVITIES_GET: 'Get activities for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_CACHE_USERS: 'Get cache users for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_CACHE_USERS_ASSIGNMENT_UPDATE: 'Update assignment for user email=[{email}]',
  NOTIFICATION_SUBJECT_DOMAIN_FEATURES_GET: 'Get features for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_FEATURE_CREATE: 'Create {featureName} feature for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_FEATURE_ENABLE: 'Enable {featureName} feature for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_FEATURE_DISABLE: 'Disable {featureName} feature for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_FEATURE_DISABLE_DATE_UPDATE: 'Update disable date for {featureName} feature for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_FEATURE_DELETE: 'Delete {featureName} feature for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_RETENTION_POLICIES: 'Get retention policies for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_RETENTION_POLICY_UPDATE: 'Update {policyType} for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_DOMAIN_STORAGE_DATA: 'Get storage data for domain id=[{domainId}]',
  NOTIFICATION_SUBJECT_USER: 'Get info for user id=[{userId}]',
  NOTIFICATION_SUBJECT_USER_FEATURES_GET: 'Get features for user id=[{userId}]',
  NOTIFICATION_SUBJECT_USER_FEATURE_UPDATE: 'Update feature for user id=[{userId}]',
  NOTIFICATION_SUBJECT_USER_BATCHES_GET: 'Get batches for user id=[{userId}]',
  NOTIFICATION_SUBJECT_USERS_LIST: 'Get list of users',
  NOTIFICATION_SUBJECT_USER_STORAGE_DATA: 'Get storage data for user id=[{userId}]',
  NOTIFICATION_SUBJECT_SCARMIN_USER: 'Get SCARMIN user info',
  NOTIFICATION_SUBJECT_PROBLEMS_LIST: 'Get list of problems',
  NOTIFICATION_SUBJECT_ERROR_CODES: 'Get list of error codes',
  NOTIFICATION_SUBJECT_DOMAIN_FEATURE_UPDATE_SETTINGS: 'Update setting {settingName} in Feature {featureName} for domain id=[{domainId}]',

  PROBLEMS_TITLE: 'Problems',
  PROBLEMS_SELECT_DATE: 'Date',
  PROBLEMS_SELECT_CODE: 'Code',
  PROBLEMS_SELECT_DOMAIN: 'Domain ID',
  PROBLEMS_SELECT_USER: 'User ID',
  PROBLEMS_BATCH_ID: 'Batch ID',
  PROBLEMS_CID: 'CID',
  PROBLEMS_JOB_ID: 'Job ID',
  PROBLEMS_CODE: 'Code',
  PROBLEMS_PARTITION_ID: 'Partition ID',
  PROBLEMS_PARTITION_ID_TOOLTIP: 'Data DB',
  PROBLEMS_OBJECT_TYPE: 'Object Type',
  PROBLEMS_TIME: 'Time',
  PROBLEMS_SOURCE: 'Source',
  PROBLEMS_SOURCE_NAME: 'Source Name',
  PROBLEMS_SUBJECT: 'Item',
  PROBLEMS_UNAVAILABLE: 'Unavailable',
  PROBLEMS_UNKNOWN_MESSAGE: 'Unknown problem code. ¯\\_(ツ)_/¯',
  PROBLEMS_LINK_COLUMN_TITLE: 'Link to problems',
  PROBLEMS_LINK: 'Go to problems',

  BACKUP: 'Backup',
  RESTORE: 'Restore',
  EXPORT: 'Export',

  TRIAL: 'Trial',
  PAID: 'Paid',
  ALL: 'All',

  UPDATE_BUTTON: 'Update',
  FORCE_UPDATE_BUTTON: 'Force Update',

  BATCHES_EMPTY_TEXT: 'No Batches',

  TIMEOUT_REQUEST_ERROR: 'Oops! Something went wrong. Please try again in few minutes or if problem persists - contact support',

  EXPECTED: 'NON ACTIONABLE',
  BONAFIDE: 'ACTIONABLE',
  SPORADIC: 'SPORADIC',
  NO_CODE_TITLE: 'No code'
};

export default en;
