sql:
  pg-driver-class-name: org.postgresql.Driver
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
    minimum-idle: 2
    idle-timeout: 30000
    pool-name: ai-database-pool
    connection-timeout: 30000
